### ISSUE TITLE
[Bug*] window 环境 运行项目失败

### ISSUE THREAD

**Issue by worklinwu** [juicecube/mlz-admin#127]
- 💻 系统信息：`window 10`

- 🦊 浏览器环境：`Google Chrome 83.0.4103.61`

- 🚛 Nodejs 版本： `v10.21.0`

- ⚛️ React 版本：`^16.12.0`

- 👣 复现方法及用例：

`npm start` 报错:  'rm' 不是内部或外部命令，也不是可运行的程序 / 'NODE_ENV' 不是内部或外部命令，也不是可运行的程序  
建议添加 rimraf 来解决 rm 问题.  添加 `cross-env` 来解决 NODE_ENV 问题

**Comment by milobluebell** [comment]
completed🏁 master分支，请测试下。 @worklinwu

**Comment by milobluebell** [comment]
因为项目做了重构，现在直接运行 `npm run reset`即可。

**Comment by milobluebell** [comment]
CLOSED with resolved
