### ISSUE TITLE
[Feature*] 课包->课期->班级->课程 组合选择框

### ISSUE THREAD

**Issue by biglemontree** [juicecube/mlz-admin#51]
**你想要添加的功能，解决哪些实际问题？必须提供简要描述**

> 课包->课期->班级->课程， 业务常用的4级选择，前项的选择会影响后面的下拉项及默认值

**你希望上述功能应如何实现？（不填视为无建议）**

> 组件外传入接口数据，组件内部重置表单值，重置下拉项，暴露onChange方法

**假如无法实现，你是否有替代方案作为建议？（不填视为无建议）**

> 比如：暂无

**是否有其它补充内容？**

**Comment by milobluebell** [comment]
收到。尽快排人排期做。

**Comment by xylvvv** [comment]
直接加入antd的Cascader组件的话符合你的要求吗？不符合的话可以提下具体的需求，比如与Cascader相比需要增加哪些改动

**Comment by milobluebell** [comment]
与业务逻辑耦合高，且副作用不少，暂时决定CLOSE。  但现有功能可以很快捷地完成该功能：

- Table组件的columns，允许传入`searchRender`/`searchKey`等字段，功能类似Antd.Table自身的columns的`render`和`dataIndex` [参考链接](https://github.com/juicecube/mlz-admin/blob/master/src/table/common-table/index.type.ts#L27)
- render的组件只需要遵守antd.Form双向绑定的约定就可以。[参考链接](https://github.com/juicecube/mlz-admin/blob/master/src/table/common-table/index.type.ts#L27)

@biglemontree
