### ISSUE TITLE
[Feature*] 类似antd的DateRange：课程进度选择器

### ISSUE THREAD

**Issue by biglemontree** [juicecube/mlz-admin#60]
**你想要添加的功能，解决哪些实际问题？必须提供简要描述**

> 课程进度选择器，期望用户可以选择from第X课to 第Y课，Y必须大于X，类似antd的DateRange

**你希望上述功能应如何实现？（不填视为无建议）**

> 可接受初始值[X, Y]自动选择课程，外部提供事件可重置value

**假如无法实现，你是否有替代方案作为建议？（不填视为无建议）**

> 比如：暂无

**是否有其它补充内容？**
![image](https://user-images.githubusercontent.com/13833202/92710337-48c30c00-f38a-11ea-808c-54c2313e2a86.png)

**Comment by biglemontree** [comment]
![image](https://user-images.githubusercontent.com/13833202/92710613-8758c680-f38a-11ea-90be-44ae79296d48.png)

**Comment by milobluebell** [comment]
Completed
